---
production:
  :concurrency: 4
development:
  :concurrency: 4

:scheduler:
  :schedule:
    open_jobs:
      cron: '0 * * * * *'   # Runs once per minute
      class: OpenBetsWorker

    close_jobs:
      cron: '0 * * * * *'   # Runs once per minute
      class: CloseBetsWorker
